all: player.c host.c bidding_system.c player_bonus.c
	gcc player.c -o player
	gcc host.c -o host
	gcc bidding_system.c -o bidding_system
	gcc player_bonus.c -o player_bonus
clean: 
	rm -f bidding_system host player player_bonus